### ISSUE TITLE
Wrong naming of `list_of_speakers` in the `models.yml`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1162]
The relation:
```yml
projector_countdown:
    used_as_list_of_speaker_countdown_meeting_id:
    [...]
```

should be named `used_as_list_of_speakers_countdown_meeting_id`.
