### ISSUE TITLE
Implement backend for list election polls

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1608]
We are implementing polls where a list of candidates can be approved/rejected through a poll.

This requires 2 new models (`poll_candidate_list` & `poll_candidate` and create and delete actions as backend-internal actions) and some other action and model changes:

****NEW MODELS:****

```
poll_candidate_list:
  id:
    type: number
    restriction_mode: A
  poll_candidate_ids:
    type: relation-list
    to: poll_candidate/poll_candidate_list_id
    restriction_mode: A
    equal_fields: meeting_id
  meeting_id:
    type: relation
    to: meeting/poll_candidate_list_ids
    required: true
    restriction_mode: A
  option_id:
    type: relation
    to: option/content_object_id
    equal_fields: meeting_id
    required: true
    restriction_mode: A
```
Note: this should become a new possible relation for the `option/content_object_id`-field.

and:
```
poll_candidate:
  id: 
    type: number
    restriction_mode: A
  poll_candidate_list_id:
    type: relation
    to: poll_candidate_list/poll_candidate_ids
    equal_fields: meeting_id
    restriction_mode: A
    required: true
  user_id:
    type: relation
    to: user/poll_candidate_ids
    required: true
    restriction_mode: A
  weight:
    type: number
    required: true
    restriction_mode: A
  meeting_id:
    type: relation
    to: meeting/poll_candidate_ids
    required: true
    restriction_mode: A
```

****NEW OR CHANGED BACKEND ACTIONS:****

**poll.create: extended Option interface**
```
Interface Option {
    // Exactly one of text, content_object_id or poll_candidate_user_ids must be given
    text: string;  // topic-poll
    content_object_id: Fqid; // must be one of  user or motion.
    poll_candidate_user_ids: [user_ids]; // sorted list of user ids for candidate list election

    // Only for type==analog, optional votes can be given
    Y?: decimal(6); // Y, YN, YNA mode
    N?: decimal(6); // N, YN, YNA mode
    A?: decimal(6); // YNA mode
}
```
The `options` should allow a list of options like before.  If poll_candidate_user_ids is filled in the options, then we have a candidate list election. The backend should then create a new `poll_candidate_list`  with `poll_candidate`s of all users in the field, the `weight` will be filled analogue the sequence of user_ids.

**Internal action: poll_candidate_list.create:**
```
{
// Required
    option_id: Id
    entries: {
        user_id: Id,
        weight: number
    }[]
}
```
Should create an `poll_candidate` for every entry in `entries` with the given user and weight.

Permissions: 
User needs `poll.can_manage` in the meeting specifiec by the `meeting_id` (indirectly specified by the `option_id`.

** Further internal actions for poll_candidate_list- and poll_candidate-collections**
Actions for 
poll_candidate_list- and poll_candidate-actions are all internal. They don't need update-actions, because it is not allowed to update these objects. Delete-actions are  needed for cascading deletes.
 
****OTHER MODEL CHANGES****
Models (derived from above):
- Option: Gets new possible type for the `content_object_id`-relation to `poll_candidate_list/option_id`
- User: new relation-list field 'poll_candidate_ids` to `poll_candidate/user_id` (restriction mode A)
- Meeting:  new relation fields `poll_candidate_list_ids`  and `poll_candidate_ids` to the respective collections (restriction mode B)

****Other****
The candidate list (and the entries) should be visible to all who can see the parent poll of the option holding the candidate list, as well as those who can create the candidate list.

**Comment by luisa-beerboom** [comment]
- There should be no update action for the candidate_list or the candidate_list entry.
- A potential delete action should only be called as a subroutine of poll.delete (or option.delete) (as in "if the options hold candidate_lists in their content_object_ids, delete all those candidate_lists along with their entries"). The purpose of this is to ensure that one can't arbitrarily empty poll options

**Comment by reiterl** [comment]
Which restriction mode have `meeting/candidate_list_ids` and `meeting/candidate_list_entry_ids`?

**Comment by reiterl** [comment]
And `user/candidate_list_entry_ids` is also missing restriction mode.

**Comment by jsangmeister** [comment]
Updated the description. Changelog:
- renamed new classes
- made new classes backend-internal
- removed `title` from the `assignment_candidate_list` (can be discussed, but I don't see any value in adding a title if a list can never be updated, manually deleted or be reused in some way)
- adjusted `assignment_candidate_list.create` payload
- changed permissions for `assignment_candidate_list.create`
- adjusted `poll.create` payload
- added restriction modes for back relations in user and meeting

@r-peschke @luisa-beerboom @rrenkert please check if these changes are okay. I also added some more detail for the actual backend implementation.

**Comment by luisa-beerboom** [comment]
@jsangmeister 

2 things:
1. I still find the new names to be confusing. Why not just make it more dynamic and use `poll` or `option` as a prefix. The name `assignment_candidate_list` just leads the reader to assume that the list holds `assignment_candidate` instances (which is supposed to be a completely separate model)
2. Why the new flag? Can't the client just pass an array of user-fqids in the desired order as a new field in the `poll.create`s option scheme? That way we wouldn't have to re-write the backend for both the assignment AND the poll.create when we eventually maybe allow for polls with multiple list-options. the payload is also a bit more similar to what currently happens and wouldn't require the `poll.create` to care about what's in the assignment-model

**Comment by jsangmeister** [comment]
> @jsangmeister
> 
> 2 things:
> 
> 1. I still find the new names to be confusing. Why not just make it more dynamic and use `poll` or `option` as a prefix. The name `assignment_candidate_list` just leads the reader to assume that the list holds `assignment_candidate` instances (which is supposed to be a completely separate model)

Ok, will change to `poll_*`. I see the ambiguity.

> 2. Why the new flag? Can't the client just pass an array of user-fqids in the desired order as a new field in the `poll.create`s option scheme? That way we wouldn't have to re-write the backend for both the assignment AND the poll.create when we eventually maybe allow for polls with multiple list-options. the payload is also a bit more similar to what currently happens and wouldn't require the `poll.create` to care about what's in the assignment-model

We need to touch the backend code anyway. The way we modeled it now, a candidate list cannot exist without an option (which, I think, is correct). So, the client cannot create a list and afterwards send it to the backend as a content object.

If we use your suggestion, we would also send redundant information: The backend knows the candidates of the assignment and their weights, so the client does not need to send it. This just leads to potential errors, e.g. if the client missed an autoupdate and sends old data, the order of the candidate list and the order of the candidates in the assignment will differ. The client should theoretically only ever send information that the backend does not have.

**Comment by jsangmeister** [comment]
Another proposed change: If we use `poll_candidate_list`, we can call the entries `poll_candidate` (with the redundant `_list_entry` suffix) without getting into any name clashes. I like it ;)

**Comment by luisa-beerboom** [comment]
@jsangmeister
> We need to touch the backend code anyway. The way we modeled it now, a candidate list cannot exist without an option (which, I think, is correct). So, the client cannot create a list and afterwards send it to the backend as a content object.
That wasn't what I was proposing, I was proposing to send the data in the poll.create payload

> If we use your suggestion, we would also send redundant information: The backend knows the candidates of the assignment and their weights, so the client does not need to send it. This just leads to potential errors, e.g. if the client missed an autoupdate and sends old data, the order of the candidate list and the order of the candidates in the assignment will differ. The client should theoretically only ever send information that the backend does not have.

If the client didn't get a certain autoupdate I don't think we would actually WANT the backend to do things accurately to how the assignment looks, as that would end up creating a different list than the one that the operator confirmed when he clicked save.
Also: If we're really going to think like this we may as well also change the way regular user-polls are created, after all: the options in those are also just generated from the assignment_candidates by the client. No information there that the backend doesn't already have, yet we still do it that way.

**Comment by jsangmeister** [comment]
Yes, I would be in favor of that :D But if we want to use your approach, we'll have to find another way to pass the information: For normal assignment polls, every option equals one assignment candidate, so the client can just pass a list of options in the payload, one for each candidate. For list polls, there is only one option with a list of users, so we cannot pass a list of options, so we have to expand the `options_schema` with another field specifically for this case, something like `poll_candidate_user_ids` and then have to check in the code that only one of `text`, `content_object_id` and the new field is given. Or do you have a better suggestion?

**Comment by jsangmeister** [comment]
Ok, @rrenkert @r-peschke any preferences from your side?

**Comment by rrenkert** [comment]
> so we have to expand the `options_schema` with another field specifically for this case, something like `poll_candidate_user_ids` and then have to check in the code that only one of `text`, `content_object_id` and the new field is given. Or do you have a better suggestion?

I can follow your arguments and completly agree.Talked to @r-peschke and he also agrees.

**Comment by reiterl** [comment]
The discussion of this issue has ended. So I will start to implement it and remove *need discussion*.

**Comment by reiterl** [comment]
The models are broken. The relations are not correct. There is no model like "candidate_list_entry" etc. I try to fix it.

**Comment by r-peschke** [comment]
To understand or implement the issue the leading comment should and I hope is sufficient after all the discussions.

**Comment by reiterl** [comment]
@r-peschke I have a problem with poll_candidate_list/option_id.
```
option:
  content_object_id:
    type: generic-relation
    to:
      - motion/option_ids
      - user/option_$_ids
      - poll_candidate_list/option_id
    equal_fields: meeting_id
    restriction_mode: A
    required: false
```
`motion/option_ids` and `user/option_$_ids` are fields with **lists**. `poll_candidate_list/option_id` is a **single id**. That seems to lead to errors in the tests.
