### ISSUE TITLE
Add new motion fields

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#2119]
Two new fields should be added to motions: an editor and a working group speaker. Both can be (de-)activated in the settings.

Proposal for `models.yml` changes:
```
meeting:
  ...
  motions_enable_editor:
    type: boolean
    restriction_mode: B
  motions_enable_working_group_speaker:
    type: boolean
    restriction_mode: B

motion:
  ...
  editor_id:
    type: relation
    to: meeting_user/editor_for_motion_ids
    equal_fields: meeting_id
    restriction_mode: B
  working_group_speaker_id:
    type: relation
    to: meeting_user/working_group_speaker_for_motion_ids
    equal_fields: meeting_id
    restriction_mode: B
```
The restriction mode B is new for motions. Only users with `motion.can_manage` should be able to see fields with this restriction mode.

The actions `motion.update` and `meeting.update` must be updated accordingly to include the new fields. The motion fields can only be updated with `motion.can_manage`, the meeting fields analogously to all other settings.
