### ISSUE TITLE
Add new user permissions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#2122]
The user permissions should be adjusted in the following way:
```
user:
    can_manage:
        can_manage_presence:
            can_see:
        can_update:
            can_see_personal_data:
                can_see:
```

The meaning of the new permissions are:
- `can_see_personal_data`: The user data is partioned into "basic" data which can be seen with `can_see` and "personal" data, which can only be seen with `can_see_personal_data`. The list of "personal data fields" is the following: `email`, **TODO**. This has to be reflected in the restriction modes of the fields and implemented in the restricter.
- `can_update`: Users with this permission can update existing users, not delete them or create new users (meaning only `user.update` can be executed).
