### ISSUE TITLE
Add presenter for users

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#412]
User for the orga level UI as quick and dirty solution: Client can send sort criteria (first_name or last_name), start index and max_number (default 100). The presenter fetches all users from DB, sorts them and sends the paginated ids to the client.

**Comment by FinnStutzenstein** [comment]
Note: Also temporary users must be received.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Please specify the presenter by giving the payload and describe what the presenter returns. After this, if you do not directly work on this, unassign yourself.

**Comment by jsangmeister** [comment]
The biggest issue I see with this is that the presenter needs to fetch ALL users everytime it is called, which may be a huge amount. But I don't have a solution for this at the moment...

**Comment by normanjaeckel** [comment]
Payload may look like this:
```yaml
start_index: number  # Sending 0 means that the server should respond entries from the beginning of the filtered list. Use higher numbers for pagination.
entries: number  # How many entries should be provides. Client may use something like 100.
sort_criteria: string[]  # A list of field names for sorting. Something like first_name or last_name The presenter should use the criteria in the given order
reverse: boolean  # If true the sorting is inverted.
```

The presenter should return only a list of ids:
```yaml
users: id[]
```
