### ISSUE TITLE
`meeting.clone`: meeting-related "settings" are not copied properly

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#963]
The meeting's settings are not copied properly.

<details>
<summary>The list of settings</summary>

<p>

```yml
  # Configuration (only for the server owner)
  jitsi_domain:
    type: string
    restriction_mode: B
  jitsi_room_name:
    type: string
    restriction_mode: B
  jitsi_room_password:
    type: string
    restriction_mode: B
  enable_chat:
    type: boolean
    restriction_mode: B

  # System
  url_name:
    type: string
    description: For unique urls.
    restriction_mode: B
  template_for_committee_id:
    type: relation
    to: committee/template_meeting_id
    restriction_mode: B
  enable_anonymous:
    type: boolean
    default: False
    restriction_mode: A
  custom_translations:
    type: JSON
    restriction_mode: B

  # Jitsi/Livestream settings
  conference_show:
    type: boolean
    default: False
    restriction_mode: C
  conference_auto_connect:
    type: boolean
    default: False
    restriction_mode: C
  conference_los_restriction:
    type: boolean
    default: False
    restriction_mode: C
  conference_stream_url:
    type: string
    restriction_mode: C
  conference_stream_poster_url:
    type: string
    restriction_mode: C
  conference_open_microphone:
    type: boolean
    default: False
    restriction_mode: C
  conference_open_video:
    type: boolean
    default: False
    restriction_mode: C
  conference_auto_connect_next_speakers:
    type: number
    default: 0
    restriction_mode: C
  conference_enable_helpdesk:
    type: boolean
    default: False
    restriction_mode: C
  applause_enable:
    type: boolean
    default: False
    restriction_mode: C
  applause_type:
    type: string
    enum:
      - applause-type-bar
      - applause-type-particles
    default: applause-type-bar
    restriction_mode: C
  applause_show_level:
    type: boolean
    default: False
    restriction_mode: C
  applause_min_amount:
    type: number
    default: 1
    minimum: 0
    restriction_mode: C
  applause_max_amount:
    type: number
    default: 0
    minimum: 0
    restriction_mode: C
  applause_timeout:
    type: number
    default: 5
    minimum: 0
    restriction_mode: C
  applause_particle_image_url:
    type: string
    restriction_mode: C

  # Projector countdown
  projector_countdown_default_time:
    type: number
    default: 60
    required: true
    restriction_mode: B
  projector_countdown_warning_time:
    type: number
    minimum: 0
    default: 0
    required: true
    restriction_mode: B

  # Exports
  export_csv_encoding:
    type: string
    enum:
      - utf-8
      - iso-8859-15
    default: utf-8
    restriction_mode: B
  export_csv_separator:
    type: string
    default: ","
    restriction_mode: B
  export_pdf_pagenumber_alignment:
    type: string
    enum:
      - left
      - right
      - center
    default: center
    restriction_mode: B
  export_pdf_fontsize:
    type: number
    enum:
      - 10
      - 11
      - 12
    default: 10
    restriction_mode: B
  export_pdf_pagesize:
    type: string
    enum:
      - A4
      - A5
    default: A4
    restriction_mode: B

  # Agenda
  agenda_show_subtitles:
    type: boolean
    default: False
    restriction_mode: B
  agenda_enable_numbering:
    type: boolean
    default: True
    restriction_mode: B
  agenda_number_prefix:
    type: string
    maxLength: 20
    restriction_mode: B
  agenda_numeral_system:
    type: string
    enum:
      - arabic
      - roman
    default: arabic
    restriction_mode: B
  agenda_item_creation:
    type: string
    enum:
      - always
      - never
      - default_yes
      - default_no
    default: default_yes
    restriction_mode: B
  agenda_new_items_default_visibility:
    type: string
    enum:
      - common
      - internal
      - hidden
    default: internal
    restriction_mode: B
  agenda_show_internal_items_on_projector:
    type: boolean
    default: True
    restriction_mode: B

  # List of speakers
  list_of_speakers_amount_last_on_projector:
    type: number
    minimum: -1
    default: 0
    restriction_mode: B
  list_of_speakers_amount_next_on_projector:
    type: number
    minimum: -1
    default: -1
    restriction_mode: B
  list_of_speakers_couple_countdown:
    type: boolean
    default: True
    restriction_mode: B
  list_of_speakers_show_amount_of_speakers_on_slide:
    type: boolean
    default: True
    restriction_mode: B
  list_of_speakers_present_users_only:
    type: boolean
    default: False
    restriction_mode: B
  list_of_speakers_show_first_contribution:
    type: boolean
    default: False
    restriction_mode: B
  list_of_speakers_enable_point_of_order_speakers:
    type: boolean
    default: False
    restriction_mode: B
  list_of_speakers_enable_pro_contra_speech:
    type: boolean
    default: False
    restriction_mode: B
  list_of_speakers_can_set_contribution_self:
    type: boolean
    default: False
    restriction_mode: B
  list_of_speakers_speaker_note_for_everyone:
    type: boolean
    default: False
    restriction_mode: B
  list_of_speakers_initially_closed:
    type: boolean
    default: False
    restriction_mode: B

  # Motions
  motions_default_workflow_id:
    type: relation
    to: motion_workflow/default_workflow_meeting_id
    required: true
    restriction_mode: B
  motions_default_amendment_workflow_id:
    type: relation
    to: motion_workflow/default_amendment_workflow_meeting_id
    required: true
    restriction_mode: B
  motions_default_statute_amendment_workflow_id:
    type: relation
    to: motion_workflow/default_statute_amendment_workflow_meeting_id
    required: true
    restriction_mode: B
  motions_preamble:
    type: string
    default: "The assembly may decide:"
    restriction_mode: B
  motions_default_line_numbering:
    type: string
    enum:
      - outside
      - inline
      - none
    default: outside
    restriction_mode: B
  motions_line_length:
    type: number
    minimum: 40
    default: 85
    restriction_mode: B
  motions_reason_required:
    type: boolean
    default: False
    restriction_mode: B
  motions_enable_text_on_projector:
    type: boolean
    default: True
    restriction_mode: B
  motions_enable_reason_on_projector:
    type: boolean
    default: True
    restriction_mode: B
  motions_enable_sidebox_on_projector:
    type: boolean
    default: False
    restriction_mode: B
  motions_enable_recommendation_on_projector:
    type: boolean
    default: True
    restriction_mode: B
  motions_show_referring_motions:
    type: boolean
    default: True
    restriction_mode: B
  motions_show_sequential_number:
    type: boolean
    default: True
    restriction_mode: B
  motions_recommendations_by:
    type: string
    restriction_mode: B
  motions_statute_recommendations_by:
    type: string
    restriction_mode: B
  motions_recommendation_text_mode:
    type: string
    enum:
      - original
      - changed
      - diff
      - agreed
    default: diff
    restriction_mode: B
  motions_default_sorting:
    type: string
    enum:
      - number
      - weight
    default: number
    restriction_mode: B
  motions_number_type:
    type: string
    enum:
      - per_category
      - serially_numbered
      - manually
    default: per_category
    restriction_mode: B
  motions_number_min_digits:
    type: number
    default: 1
    restriction_mode: B
  motions_number_with_blank:
    type: boolean
    default: False
    restriction_mode: B
  motions_statutes_enabled:
    type: boolean
    default: False
    restriction_mode: B
  motions_amendments_enabled:
    type: boolean
    default: False
    restriction_mode: B
  motions_amendments_in_main_list:
    type: boolean
    default: True
    restriction_mode: B
  motions_amendments_of_amendments:
    type: boolean
    default: False
    restriction_mode: B
  motions_amendments_prefix:
    type: string
    default: "-"
    restriction_mode: B
  motions_amendments_text_mode:
    type: string
    enum:
      - freestyle
      - fulltext
      - paragraph
    default: paragraph
    restriction_mode: B
  motions_amendments_multiple_paragraphs:
    type: boolean
    default: True
    restriction_mode: B
  motions_supporters_min_amount:
    type: number
    minimum: 0
    default: 0
    restriction_mode: B
  motions_export_title:
    type: string
    default: Motions
    restriction_mode: B
  motions_export_preamble:
    type: string
    restriction_mode: B
  motions_export_submitter_recommendation:
    type: boolean
    default: False
    restriction_mode: B
  motions_export_follow_recommendation:
    type: boolean
    default: False
    restriction_mode: B

  # Motion poll
  motion_poll_ballot_paper_selection:
    type: string
    enum:
      - NUMBER_OF_DELEGATES
      - NUMBER_OF_ALL_PARTICIPANTS
      - CUSTOM_NUMBER
    default: CUSTOM_NUMBER
    restriction_mode: B
  motion_poll_ballot_paper_number:
    type: number
    default: 8
    restriction_mode: B
  motion_poll_default_type:
    type: string
    default: analog
    restriction_mode: B
  motion_poll_default_100_percent_base:
    type: string
    default: YNA
    restriction_mode: B
  motion_poll_default_group_ids:
    type: relation-list
    to: group/used_as_motion_poll_default_id
    restriction_mode: B

  # Users
  users_sort_by:
    type: string
    enum:
      - first_name
      - last_name
      - number
    default: first_name
    restriction_mode: B
  users_enable_presence_view:
    type: boolean
    default: False
    restriction_mode: B
  users_enable_vote_weight:
    type: boolean
    default: False
    restriction_mode: B
  users_allow_self_set_present:
    type: boolean
    default: False
    restriction_mode: B
  users_pdf_welcometitle:
    type: string
    default: Welcome to OpenSlides
    restriction_mode: B
  users_pdf_welcometext:
    type: string
    default: "[Place for your welcome and help text.]"
    restriction_mode: B
  users_pdf_url:
    type: string
    default: http://example.com:8000
    restriction_mode: B
  users_pdf_wlan_ssid:
    type: string
    restriction_mode: B
  users_pdf_wlan_password:
    type: string
    restriction_mode: B
  users_pdf_wlan_encryption:
    type: string
    enum:
      - ""
      - WEP
      - WPA
      - nopass
    restriction_mode: B
  users_email_sender:
    type: string
    default: OpenSlides
    restriction_mode: B
  users_email_replyto:
    type: string
    restriction_mode: B
  users_email_subject:
    type: string
    default: OpenSlides access data
    restriction_mode: B
  users_email_body:
    type: string
    default: >-
      Dear {name},



      this is your personal OpenSlides login:

          {url}

          username: {username}

          password: {password}



      This email was generated automatically.
    restriction_mode: B

  # Assignments
  assignments_export_title:
    type: string
    default: Elections
    restriction_mode: B
  assignments_export_preamble:
    type: string
    restriction_mode: B

  # Assignment polls
  assignment_poll_ballot_paper_selection:
    type: string
    enum:
      - NUMBER_OF_DELEGATES
      - NUMBER_OF_ALL_PARTICIPANTS
      - CUSTOM_NUMBER
    default: CUSTOM_NUMBER
    restriction_mode: B
  assignment_poll_ballot_paper_number:
    type: number
    default: 8
    restriction_mode: B
  assignment_poll_add_candidates_to_list_of_speakers:
    type: boolean
    default: True
    restriction_mode: B
  assignment_poll_sort_poll_result_by_votes:
    type: boolean
    default: True
    restriction_mode: B
  assignment_poll_default_type:
    type: string
    default: analog
    restriction_mode: B
  assignment_poll_default_method:
    type: string
    restriction_mode: B
  assignment_poll_default_100_percent_base:
    type: string
    default: valid
    restriction_mode: B
  assignment_poll_default_group_ids:
    type: relation-list
    to: group/used_as_assignment_poll_default_id
    restriction_mode: B

  # Polls
  poll_ballot_paper_selection:
    type: string
    enum:
      - NUMBER_OF_DELEGATES
      - NUMBER_OF_ALL_PARTICIPANTS
      - CUSTOM_NUMBER
    restriction_mode: B
  poll_ballot_paper_number:
    type: number
    restriction_mode: B
  poll_sort_poll_result_by_votes:
    type: boolean
    restriction_mode: B
  poll_default_type:
    type: string
    default: analog
    restriction_mode: B
  poll_default_method:
    type: string
    restriction_mode: B
  poll_default_100_percent_base:
    type: string
    default: YNA
    restriction_mode: B
  poll_default_group_ids:
    type: relation-list
    to: group/used_as_poll_default_id
    restriction_mode: B
  poll_couple_countdown:
    type: boolean
    default: True
    restriction_mode: B
```

</p>
</details>
